export const SITE_META = {
  name: `Supereasy Game`,
  url: ``,
  domain: ``,
};

export const API_URL = ``;

export const CHANNEL = `youletech`;

export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=${CHANNEL}&appid=`;
export const ICON_PATH = `https://cdn.iwantalipstick.com/gameicon2/`;

export const GA_ID = `G-DDF82DXW7Z`;

export const ADS_ID = `ca-pub-9209477879340784`;
export const ADS_SLOT_ID = {
  home: `8841942463`,
  category: `2623469732`,
  detail: `7528860791`,
};

export const SELECTED_GAMES = [
  "BigSword",
  "BoardTheTrain",
  "FireTheGun",
  "MergeGuns3D",
  "FeverRacing",
  "ColorBall3D",
  "ZombieSurvival",
  "CrazyMoto",
  "CrazyKart3D",
  "LetMeIn",
  "BumbleShooter",
  "Knife",
  "HiTaxi",
  "TrafficRun",
  "BulletMaster3D",
  "MrRacer",
  "MagicParkour",
  "FrozenMagic",
  "MrBullet",
  "JumpSmash",
  "CrazyKnife",
  "TrafficPassing",
  "SuperThrow",
  "AceMan",
  "BatterKing",
  "GoldenGlove",
  "KnockBalls",
  "CrashTower3D",
  "DragonCrush",
  "HungryAnimals",
  "SnakeGo",
  "DessertConnect",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "ColorRing",
  "PianoKeys",
  "ArchersKing",
  "MyBabyCare",
  "DartsKing3D",
  "CrazyRace",
  "BallIsComing",
  "HungyBunny",
  "TheSameWorld",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BlockGun3D",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AirBrawl",
  "AmazingRoad",
  "RainbowSplash",
  "CrazyDrift",
  "FruitsFall",
  "RocketJump",
  "MagicPaint",
  "GlidingCharger",
  "RoadCharger",
  "ArcheryMaster",
  "UltraDrift",
  "SharkIsComing",
  "PuppyRun",
  "PenguinDash",
  "MonsterCrash",
  "DeathJump",
  "HungryMonster",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "VirusWar",
  "TrappedPirate",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "GunShooter",
  "TowerBlast3D",
  "ShootSmash",
  "ShootingCubes",
  "BubbleBlast",
  "FlyPass",
  "KillAllZombies",
  "CollectColorfulBalls",
  "KimbapRun",
  "AnipopLink",
  "PetsMatch",
  "HappyBilliards",
  "CrazyBomb",
  "HelpTheZombie",
  "SaveThePets",
  "SoccerHero",
  "TableTennisChampionship",
  "MagicDonuts",
  "SolitaireClassic",
  "DeathRun",
  "IdleRestaurantTycoon",
  "ImEmpire",
  "MahjongConnect",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "TwistyRoad",
  "ZooBlast",
  "ZumaMarbles",
  "BlockPuzzle",
  "CrazyPortal",
  "DressQueen",
  "MahjongLink3D",
  "MergeAndDefense",
  "MergeMagicJewellery",
  "PetRun",
  "SkyRunning3D",
  "SuperGolf",
  "TowerDefenseX",
  "PandaRescue",
  "FillTheGlass",
  "MagicNumber",
  "PlantBeatZombies",
  "AirHockey3D",
  "MyBowling3D",
  "Chess3D",
  "8BallKing",
  "MyUnicorn",
  "MagicJigsaw",
  "FairyTalesPuzzle",
  "PipePuzzle",
  "SplittingCells",
  "FeedMaster",
  "FinalBattle",
  "SuperDefense",
  "Super2048",
  "BubblePop",
  "RelivedLife",
  "CandyHit",
  "MergeCat",
  "MelodyLink",
  "PuzzleVenture",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "HappyTetris",
  "MagicPainter",
  "MatchingCook",
  "ColorBead",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
];

export const EXCLUDED_GAMES = [];

export const FEATURED_GAMES = [];
