export const SHOW_AD = true;

export const SITE_META = {
  name: `Supereasy Game`,
  url: `https://www.supereasygame.com`,
  domain: `supereasygame.com`,
};

export const DATA_MODE = ``; // 设置为 renew 即可强制更新

export const DEV_MODE = false; // 设置为 true 开启adtest

export const CHANNEL = `mcy`;

// export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=${CHANNEL}&appid=`;
export const GAME_PATH = `https://cdn2.supereasygame.com/newgames/minigame.html?platform=${CHANNEL}&appid=`;
export const ICON_PATH = `https://cdn.iwantalipstick.com/gameicon2/`;

export const GA_ID = `G-E8BGRZK893`;
// export const GA_ID2 = ``;

export const ADS_ID = `ca-pub-9209477879340784`;

export const ADS_SLOT_ID = {
  home: `2414717568`,
  category: `8112453720`,
  detail: `8112453720`,
};

export const SELECTED_GAMES = [
  "Knife",
  "JumpSmash",
  "CrazyMoto",
  "CrazyKart3D",
  "FireTheGun",
  "FeverRacing",
  "ColorBall3D",
  "CrazyKnife",
  "BoardTheTrain",
  "MrRacer",
  "BigSword",
  "HiTaxi",
  "TrafficRun",
  "MrBullet",
  "LetMeIn",
  "SnakeGo",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "GoldenGlove",
  "PianoKeys",
  "ArchersKing",
  "BallIsComing",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BatterKing",
  "BlockGun3D",
  "ZombieSurvival",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AceMan",
  "AirBrawl",
  "BumbleShooter",
  "AmazingRoad",
  "RainbowSplash",
  "MagicParkour",
  "CrazyDrift",
  "FruitsFall",
  "MagicPaint",
  "RoadCharger",
  "ArcheryMaster",
  "SharkIsComing",
  "PuppyRun",
  "HungryMonster",
  "HungryAnimals",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "GunShooter",
  "MergeGuns3D",
  "BulletMaster3D",
  "ShootSmash",
  "ShootingCubes",
  "BubbleBlast",
  "FlyPass",
  "KillAllZombies",
  "AnipopLink",
  "PetsMatch",
  "CrazyBomb",
  "HelpTheZombie",
  "SaveThePets",
  "SoccerHero",
  "TableTennisChampionship",
  "SolitaireClassic",
  "DeathRun",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "TwistyRoad",
  "ZooBlast",
  "CrazyPortal",
  "MahjongLink3D",
  "MergeAndDefense",
  "PetRun",
  "SkyRunning3D",
  "SuperGolf",
  "TowerDefenseX",
  "FillTheGlass",
  "PlantBeatZombies",
  "MyBowling3D",
  "8BallKing",
  "PipePuzzle",
  "TrafficPassing",
  "SplittingCells",
  "FeedMaster",
  "FinalBattle",
  "FrozenMagic",
  "SuperDefense",
  "Super2048",
  "BubblePop",
  "RelivedLife",
  "MelodyLink",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "HappyTetris",
  "MagicPainter",
  "MatchingCook",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
  "OpenFire",
  "BlockMaster",
  "PouringBall",
  "EasyCharger",
  "CopyLaser",
  "LostInLust",
  "BattleBurger",
  "GravityBowling",
  "MagicCarpenter",
  "MyCat",
  "IslandSurvival",
  "HamsterRun",
  "NastyBomb",
  "DashCat",
  "CleverJump",
  "BigEater",
  "CrayonPop",
  "ColorCrash",
  "BuilderRun",
  "WildRoll",
  "RoofRunner",
  "MadEraser",
  "HarvestStory",
  "CityExpress",
  "FreeFall",
  "MyHome",
  "MagicWorm",
  "RollingBall",
  "HelpTheFish",
  "TrainIsComing",
  "SpinTheMaze",
  "CutMaster",
  "CountingMaster",
  "CleverRescue",
  "AttackHero",
  "NoneLess",
  "SuperArcher",
  "FutureWarrior",
  "SuperSoccer",
  "DigEscape",
  "TinyWar",
  "ShootingStar",
  "ColorHammer",
  "BilliardKing",
  "MagicBomb",
  "BestShooter",
  "ArcheryKing",
  "RushAndFire",
  "BestSniper",
  "SnakeHit",
  "BraveArcher",
  "PowerShooter",
  "GoldenBoot",
  "SuperCoaster",
  "SausageRun",
  "Hurricane",
  "InfiDefense",
  "BoomingPlant",
  "IceEscape",
  "HumanTower",
  "SkatingMaster",
];

export const EXCLUDED_GAMES = ["LittelBoxer"];

export const FEATURED_GAMES = ["SuperSoccer", "DashCat"];
